Search.appendIndex(
    [
                {
            "fqsen": "\\Category",
            "name": "Category",
            "summary": "",
            "url": "classes/Category.html"
        },                {
            "fqsen": "\\Category\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Category.html#method___construct"
        },                {
            "fqsen": "\\Category\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/Category.html#method_getName"
        },                {
            "fqsen": "\\Category\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "",
            "url": "classes/Category.html#method_setName"
        },                {
            "fqsen": "\\Category\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "",
            "url": "classes/Category.html#method_getDescription"
        },                {
            "fqsen": "\\Category\u003A\u003AsetDescription\u0028\u0029",
            "name": "setDescription",
            "summary": "",
            "url": "classes/Category.html#method_setDescription"
        },                {
            "fqsen": "\\Category\u003A\u003AgetOrder\u0028\u0029",
            "name": "getOrder",
            "summary": "",
            "url": "classes/Category.html#method_getOrder"
        },                {
            "fqsen": "\\Category\u003A\u003AsetOrder\u0028\u0029",
            "name": "setOrder",
            "summary": "",
            "url": "classes/Category.html#method_setOrder"
        },                {
            "fqsen": "\\Category\u003A\u003AaddToList\u0028\u0029",
            "name": "addToList",
            "summary": "add\u0020object\u0020to\u0020array",
            "url": "classes/Category.html#method_addToList"
        },                {
            "fqsen": "\\Category\u003A\u003AsortToList\u0028\u0029",
            "name": "sortToList",
            "summary": "sort\u0020the\u0020array\u0020in\u0020field\u0020\u0022order\u0022",
            "url": "classes/Category.html#method_sortToList"
        },                {
            "fqsen": "\\Category\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Category.html#property_name"
        },                {
            "fqsen": "\\Category\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/Category.html#property_description"
        },                {
            "fqsen": "\\Category\u003A\u003A\u0024order",
            "name": "order",
            "summary": "",
            "url": "classes/Category.html#property_order"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
